### ISSUE TITLE
Fix the logic for displaying thread_pools

### ISSUE THREAD

**Issue by hackerpants** [tlcowling/puppet-nginx#15]
thread_pools in the nginx config is a collection of keys and values associated with a name
i think something like a nested map is the way to go.. 
```
thread_pools:
  bob:
    thread_count: 100
    max_queue: 10
  bob2:
    thread_count: 101
    max_queue: 2
```
that way we get threadpool name uniqueness for free and a concise way to declare them.
