### ISSUE TITLE
Proper treatment of gzip

### ISSUE THREAD

**Issue by hackerpants** [tlcowling/puppet-nginx#28]
Looking at some of the standard modules I think it makes sense to document the core varaibles as params in classes.  In a more common module (such as gzip) perhaps I can make do with the 'include' pattern for the time being:

something like this:

a defined type to represent a generic 'include'
```puppet
define include (
   Array[String] $user_lines,     # non optional because a user must specify something
) {
  file { 'blahblah':
    # save in user includes.
  }
}
```

Then hiera include in the standard way:
```yaml
server:
  include:
    - uniquenameinclude
    - uniquenameinclude2
```
